eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8089/eureka/
  instance:
    hostname: localhost


microservice:
  car:
    endpoints:
      endpoint: http://CAR-MS/api/car-ms/
  location:
    endpoints:
      endpoint: http://LOCATION-MS/api/location-ms/
  user:
    endpoints:
      endpoint: http://USER-MS/api/user-ms/
