eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8089/eureka/
  instance:
    hostname: localhost

microservice:
  user:
    endpoints:
      endpoint: http://USER-SERVICE/user/
  department:
    endpoints:
      endpoint: http://DEPARTMENT-SERVICE/department/
